language: c

compiler: gcc

env:
   matrix:
      - PGBRANCH=master
      - PGBRANCH=REL_14_STABLE
      - PGBRANCH=REL_13_STABLE
      - PGBRANCH=REL_12_STABLE
      - PGBRANCH=REL_11_STABLE
      - PGBRANCH=REL_10_STABLE
      - PGBRANCH=REL9_6_STABLE
      - PGBRANCH=REL9_5_STABLE
      - PGBRANCH=REL9_4_STABLE
      - PGBRANCH=REL9_3_STABLE
      - PGBRANCH=REL9_2_STABLE
      - PGBRANCH=REL9_1_STABLE

before_install:
   - sudo service postgresql stop
   - CURDIR=$(pwd)
   - PGHOME=${CURDIR}/${PGBRANCH}
   - PGDATA=${PGHOME}/data
   - git clone https://github.com/postgres/postgres.git
   - cd postgres
   - git checkout ${PGBRANCH}
   - ./configure --prefix=${PGHOME} --enable-debug --enable-cassert
   - make -j 2
   - make install
   - export PATH=${PATH}:${PGHOME}/bin
   - initdb -D ${PGDATA} --locale=C --encoding=UTF8
   - pg_ctl -D ${PGDATA} -w start

before_script:
   - cd ${CURDIR}
   - mkdir opt
   - PG_CONFIG=${PGHOME}/bin/pg_config
   - SENNA_INS=${CURDIR}/opt/senna-1.1.2-fast
   - SENNA_CFG=${SENNA_INS}/bin/senna-cfg
   - git clone https://scm.osdn.net/gitroot/pgbigm/pg_bigm.git
   - cd pg_bigm
   - make USE_PGXS=1 PG_CONFIG=${PG_CONFIG} install
   - cd ${CURDIR}
   - git clone https://scm.osdn.net/gitroot/ludiafuncs/senna-1.1.2-fast.git
   - cd senna-1.1.2-fast
   - ./configure --prefix=${SENNA_INS} --without-mecab
   - make install
   - cd ${CURDIR}
   - make USE_PGXS=1 PG_CONFIG=${PG_CONFIG} SENNA_CFG=${SENNA_CFG} PGS2_DEBUG=1 install

script:
   - make USE_PGXS=1 PG_CONFIG=${PG_CONFIG} SENNA_CFG=${SENNA_CFG} PGS2_DEBUG=1 installcheck
   - make USE_PGXS=1 PG_CONFIG=${PG_CONFIG} SENNA_CFG=${SENNA_CFG} PGS2_DEBUG=1 installcheck-bigm

after_script:
   - if [ -f regression.diffs ]; then cat regression.diffs; fi
   - pg_ctl -D ${PGDATA} stop

notifications:
   email:
      on_success: change
      on_failure: always
